### ISSUE TITLE
Using a fixed name for simulators like `devicesim-1` can break `integration-tests`

### ISSUE THREAD

**Issue by SeanCondon** [onosproject/onos-test#135]
Integration tests required 2 simulators to be present in the cluster. They are usually created with
```
onit add simulator
onit add simulator
```
> Simulators are usually named like `device-2727455432` in this case

However adding with a given name like the following seems to cause unexplained failures in the tests
```
onit add simulator devicesim-1
onit add simulator devicesim-2
```
This issue was raised to keep track of it - it might be related to some hardcoded expectation of a name length or pattern. Needs investigation

**Comment by ray-milkey** [comment]
I am unable to reproduce this behavior. This is what I did:

 kind delete cluster && kind create cluster
make kind && onit create cluster && onit add simulator devicesim-1 && onit add simulator devicesim-2
onit run suite integration-tests

**Comment by SeanCondon** [comment]
If all that worked, then there's no issue now - closing
