### ISSUE TITLE
onit v2.0: "onit create cluster" command does not accept a name

### ISSUE THREAD

**Issue by adibrastegarnia** [onosproject/onos-test#157]
@kuujo 

It looks like when we create a cluster in the new version of onit, we cannot give a name to `onit create cluster` command (the default name which is given to the cluster is onos). Given that, we cannot create the second cluster because of this bug. If we run the command for the second time: 

```
onit create cluster
‣ 2019-11-19T16:17:07-05:00 onos Setup ONOS cluster
‣ 2019-11-19T16:17:07-05:00 onos Setup namespace
✓ 2019-11-19T16:17:07-05:00 onos Setup namespace
‣ 2019-11-19T16:17:07-05:00 onos Set up RBAC
✓ 2019-11-19T16:17:07-05:00 onos Set up RBAC
✓ 2019-11-19T16:17:07-05:00 onos Setup ONOS cluster
‣ 2019-11-19T16:17:07-05:00 onos Setup Atomix controller
✗ 2019-11-19T16:17:07-05:00 onos Setup Atomix controller
Error: deployments.apps "atomix-controller" already exists
deployments.apps "atomix-controller" already exists
```

**Comment by yeya24** [comment]
Is it a bug? If you don't specify an ID in the `onit create cluster`, it will automatically generate an UUID for you. So the namespace should not be duplicate. Do I miss something?

**Comment by adibrastegarnia** [comment]
Actually, I just noticed there is a -c option which is added in the new version.
