### ISSUE TITLE
Provide means of deleting a device via onit cli

### ISSUE THREAD

**Issue by KramKroc** [onosproject/onos-test#180]
As a test engineer I would like the ability to delete a device via onit so that I can easily tear down a device with one command and not rely on issuing multiple k8s commands.

Only options at present are to delete the onit installation via `onit delete cluster` or to delete via k8s which means you first need to delete via `onos topo remove device <device id>` and then `kubectl delete pod <pod id>`, `kubectl delete configmap <config id>` etc

**Comment by adibrastegarnia** [comment]
@KramKroc 
When you add a simulator/network the devices will be added automatically to the topo store. In addition, when you remove a simulator/network the devices will be removed automatically from topo store like this:
`onit remove simulator -n <name-of-simulator> -c <name-of-cluster>`

In addition to that, you can execute onos commands using the following command:
`onit exec -- onos topo remove device <device-id>`

I hope it helps.

**Comment by adibrastegarnia** [comment]
@KramKroc 
Please reopen it, if my answer is not the answer you were looking for.
