### ISSUE TITLE
Running "onit add simulator" a second time does not create a config in onos-config

### ISSUE THREAD

**Issue by SeanCondon** [onosproject/onos-test#71]
I ran 
```onit add simulator devicesim1```
and a few minutes later I ran
```onit add simulator devicesim2```

but when I run
```onos config get configs```
I only see the first one
```
~ $ onos config get configs
devicesim1-1.0.0	(devicesim1)	1.0.0	Devicesim	2019-08-15T09:11:05Z
	wupuOO6KMFdE8Tq1elu/qmQ29a0=
~ $ 
```

I tried this with automatic name assignment and it did **not** seem to give the same problem

**Comment by adibrastegarnia** [comment]
closed since it is not reproducible any more. We will open it if it happens again.
